### PR TITLE
Configuration variable to allow CORS over plain http

### PR DESCRIPTION
**Pull request by cquiroz**
In some cases, local dev, it would be useful to support CORS over plain http
This PR adds support for that defaulting to requiring CORS

### CODE REVIEW

**Comment by swalker2m** [comment]
Since all I know about Coors is that it is kind of a cheap beer, if this is merged and I do nothing, will everything continue to work for development the way it always has?

**Comment by toddburnside** [comment]
What are you having trouble with in local dev, Carlos?

**Comment by cquiroz** [comment]
playground doesn't work locally as we have plain http by default
Also @dngomez  is having some troubles with CORS for development of navigate

**Comment by cquiroz** [comment]
> Since all I know about Coors is that it is kind of a cheap beer, if this is merged and I do nothing, will everything continue to work for development the way it always has?

The default is the same as now, but you have flexibility to change the way it works

**Comment by toddburnside** [comment]
> playground doesn't work locally as we have plain http by default

Hmm. Interesting. Playground works for me at http://localhost:8082/playground.html

**Review by toddburnside — APPROVED** [review]
Seems fine to me.

**Comment by swalker2m** [comment]
> Hmm. Interesting. Playground works for me at http://localhost:8082/playground.html

**Comment by toddburnside** [comment]
And in explore, I use:

>    "odbURI": "ws://localhost:8082/ws",
    "odbRestURI": "http://localhost:8082",

Is Diego having trouble from server to server? Or navigate UI to ODB server?

**Comment by cquiroz** [comment]
> Is Diego having trouble from server to server? Or navigate UI to ODB server?
Navigate UI to server
Note that ws does't use CORS that's why it works with explore

**Pull request merged**
