### PR TITLE
change comments to doc strings

### LINKED ISSUE #35: schema doc has turned into comments
We need to turn `# foo` into `"foo"` in the schema so users will be able to see it.

### PR DESCRIPTION
**Pull request by tpolecat**
resolves #35 

The issue was that non-doc comments were also turned into doc, resulting in multiple consecutive doc strings, which isn't legal (or at least doesn't parse). Searching for `"""[\n\s]+"""` revealed the gaps between consecutive doc strings and from there it was easy to fix.

### CODE REVIEW

**Review by toddburnside — APPROVED** [review]
It's hard to really review that big of a diff, but LGTM

**Comment by swalker2m** [comment]
> The issue was that non-doc comments were also turned into doc, resulting in multiple consecutive doc strings, which isn't legal (or at least doesn't parse)

What are multiple consecutive doc strings?

Does this incorporate the latest schema changes?  If not, maybe I can update the script that produced it to fix the error.

**Comment by tpolecat** [comment]
@swalker2m the issue was that

```graphql
# Commented out field
# field: Type

# Non-commented field
field: Type
```

would become

```graphql
"""
Commented out field
field: Type
"""

"""Non-commented field"""
field: Type
```

And that's not legal GraphQL. There were only a few instances of this so I just fixed them by hand.

This is built against `main` so it should be up to date.

**Comment by swalker2m** [comment]
> This is built against main so it should be up to date.

Thanks, I see.  :+1:

**Pull request merged**
